language: node_js

node_js:
  - "0.10"
  - "0.12"


notifications:
  email:
    - andychilton@gmail.com
  irc:
    channels:
      - "irc.dollyfish.net.nz.org#chilts"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false
